# Generated by Django 5.1.6 on 2025-05-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='original/')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='processed/')),
                ('width', models.FloatField(null=True)),
                ('height', models.FloatField(null=True)),
                ('unit', models.CharField(choices=[('mm', 'Millimeters'), ('cm', 'Centimeters'), ('in', 'Inches')], default='px', max_length=10)),
                ('dpi', models.IntegerField(default=300)),
                ('remove_background', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
